name: Run fast_commits.rs

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  run-rust:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Build fast_commits.rs
        run: rustc fast_commits.rs -o fast_commits

      - name: Run fast_commits
        run: ./fast_commits
